version: "3"

networks: 
  go-micro:
    driver: bridge

volumes: 
  postgresql:
    driver: local
  pgadmin:
    driver: local

services: 
  # PostgreSQL Database
  postgresql:
    container_name: postgresql2
    image: postgres:10-alpine
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgresql2
    volumes: 
      - postgresql:/data/postgresql2
    ports: 
      - "5433:5432"
    networks: 
      - go-micro
    restart: unless-stopped
  
  #PostgreSQL Admin
  pgadmin:
    container_name: pgadmin2
    image: dpage/pgadmin4:5
    depends_on: 
      - postgresql
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@example.com 
      PGADMIN_DEFAULT_PASSWORD: admin 
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes: 
      - pgadmin:/root/.pgadmin2
    ports: 
      - "9090:80"
    networks: 
      - go-micro 
    links:
      - postgresql
    restart: unless-stopped
